"""
    LatticeAut(a::AbstractMatrix{Int})

The automorphism of the index lattice induced by a symmetry, given by an integer
matrix. Callable on an index or a tuple of indices.

See also: [`Cocycle`](@ref) and [`GroupElement`](@ref).
"""
struct LatticeAut{N}
    matrix :: StaticArrays.SMatrix{N,N,Int}
end

LatticeAut(a::AbstractMatrix{Int}) = LatticeAut(StaticArrays.SMatrix{size(a)...,Int}(a))

(A::LatticeAut{1})(k::Integer) = A.matrix[1] * k
(A::LatticeAut{2})(k::NTuple{2,Integer}) =
    (A.matrix[1,1]*k[1] + A.matrix[1,2]*k[2],
     A.matrix[2,1]*k[1] + A.matrix[2,2]*k[2])
(A::LatticeAut{3})(k::NTuple{3,Integer}) =
    (A.matrix[1,1]*k[1] + A.matrix[1,2]*k[2] + A.matrix[1,3]*k[3],
     A.matrix[2,1]*k[1] + A.matrix[2,2]*k[2] + A.matrix[2,3]*k[3],
     A.matrix[3,1]*k[1] + A.matrix[3,2]*k[2] + A.matrix[3,3]*k[3])
function (A::LatticeAut{N})(k::NTuple{N,Integer}) where {N}
    l = A.matrix * StaticArrays.SVector{N}(k)
    return ntuple(i -> l[i], Val(N))
end

Base.:*(A::LatticeAut, B::LatticeAut) = LatticeAut(A.matrix * B.matrix)

Base.:(==)(A::LatticeAut, B::LatticeAut) = A.matrix == B.matrix

Base.hash(A::LatticeAut, h::UInt) = hash(A.matrix, h)

#

"""
    Cocycle(amplitude::Number, phase::AbstractVector{Rational{Int}})

The factor ``\\alpha_g(k) = \\rho e^{i\\pi\\langle\\varphi,k\\rangle}`` given by
an `amplitude` ``\\rho`` and a phase ``\\varphi`` (measured in units of ``\\pi``
and stored modulo 2).

Together with a [`LatticeAut`](@ref) ``\\beta_g`` it defines the right action

```math
(g \\cdot a)_k = \\alpha_g(k) \\, a_{\\beta_g(k)},
```

under which ``\\alpha`` is not itself a group action but a 1-cocycle:
``\\alpha_{gh}(k) = \\alpha_g(\\beta_h(k))\\,\\alpha_h(k)``. Since a finite
group forces ``\\alpha_g(k)^{|G|} = 1``, `amplitude` should be a root of unity.

Fields:
- `amplitude :: T`
- `phase :: SVector{N,Rational{Int}}`

See also: [`LatticeAut`](@ref) and [`GroupElement`](@ref).
"""
struct Cocycle{N,T<:Number}
    amplitude :: T
    phase     :: StaticArrays.SVector{N,Rational{Int}} # factor of π
    Cocycle{N,T}(amplitude::T, phase::StaticArrays.SVector{N,Rational{Int}}) where {T<:Number,N} = new{N,T}(amplitude, mod.(phase, 2))
end

Cocycle(amplitude::T, phase::StaticArrays.SVector{N,Rational{Int}}) where {T<:Number,N} = Cocycle{N,T}(amplitude, phase)

Cocycle(amplitude::Number, phase::AbstractVector{Rational{Int}}) = Cocycle(amplitude, StaticArrays.SVector{length(phase),Rational{Int}}(phase))

(v::Cocycle{1,<:Interval})(k::Integer) = v.amplitude * cispi(interval(exact(v.phase[1]) * exact(k)))
(v::Cocycle{N,<:Interval})(k::NTuple{N,Integer}) where {N} = v.amplitude * cispi(interval(mapreduce(*, +, exact.(v.phase), exact.(k))))
(v::Cocycle)(k) = v.amplitude * cispi(mapreduce(*, +, v.phase, k))

Base.:(==)(v::Cocycle, w::Cocycle) = (v.amplitude == w.amplitude) & (v.phase == w.phase)

Base.hash(v::Cocycle, h::UInt) = hash(v.amplitude, hash(v.phase, h))

#

"""
    GroupElement(lattice_aut::LatticeAut, cocycle::Cocycle)

Combine a [`LatticeAut`](@ref) ``\\beta_g`` with the [`Cocycle`](@ref)
``\\alpha_g`` so that `g` defines the right action on a sequence

```math
(g \\cdot a)_k = \\alpha_g(k) \\, a_{\\beta_g(k)}.
```

Elements compose with `∘`.

Fields:
- `lattice_aut :: LatticeAut{N}`
- `cocycle :: Cocycle{N,T}`

See also: [`LatticeAut`](@ref), [`Cocycle`](@ref), [`Group`](@ref) and
[`SymmetricSpace`](@ref).
"""
struct GroupElement{N,T<:Number}
    lattice_aut :: LatticeAut{N}
    cocycle     :: Cocycle{N,T}
end

# (h·(g·a))_k = α_h(k) (g·a)_{β_h k} = α_h(k) α_g(β_h k) a_{β_g β_h k},
# and ⟨φ_g, β_h k⟩ = ⟨β_hᵀφ_g, k⟩
Base.:∘(g::GroupElement, h::GroupElement) = GroupElement(
    g.lattice_aut * h.lattice_aut,
    Cocycle(g.cocycle.amplitude * h.cocycle.amplitude,
            h.lattice_aut.matrix' * g.cocycle.phase + h.cocycle.phase))

Base.:(==)(g::GroupElement, h::GroupElement) = (g.lattice_aut == h.lattice_aut) & (g.cocycle == h.cocycle)
Base.hash(g::GroupElement, h::UInt) = hash(g.lattice_aut, hash(g.cocycle, h))

#

"""
    Group(g::GroupElement, h::GroupElement...)

The group generated by the given elements. It is closed under composition at
construction, so [`elements`](@ref) returns every element and not only the
generators.

See also: [`GroupElement`](@ref) and [`SymmetricSpace`](@ref).
"""
struct Group{N,T<:Number}
    elements :: Set{GroupElement{N,T}}
    # a `Group` is never mutated once closed, so its hash is computed once here
    # storing the hash helps with every lookup in `_orbit_cache` when constructing symmetric spaces
    hash     :: UInt
    global function unsafe_group!(elements::Set{GroupElement{N,T}}) where {N,T<:Number}
        # modify in-place the input set of group elements until it is closed under composition (O(|G|²))
        changed = true
        while changed
            changed = false
            for g ∈ elements, h ∈ elements
                gh = g ∘ h
                if gh ∉ elements
                    push!(elements, gh)
                    changed = true
                end
            end
        end
        return new{N,T}(elements, hash(elements))
    end
end

Group(g::GroupElement{N,T}, h::GroupElement{N,T}...) where {N,T<:Number} = unsafe_group!(Set{GroupElement{N,T}}((g, h...)))

"""
    elements(g::Group)

Return the set of [`GroupElement`](@ref)s of `g`. The group is closed under
composition at construction, so this is the full group and not just the
generators it was built from.

See also: [`Group`](@ref) and [`symmetry`](@ref).
"""
elements(g::Group) = g.elements

Base.:(==)(G₁::Group, G₂::Group) = G₁ === G₂ || (G₁.hash == G₂.hash && elements(G₁) == elements(G₂)) # elements(G₁) == elements(G₂) is a safeguard
Base.issubset(G₁::Group, G₂::Group) = issubset(elements(G₁), elements(G₂))
function Base.intersect(G₁::Group, G₂::Group)
    G₁ == G₂ && return G₁
    return unsafe_group!(intersect(elements(G₁), elements(G₂)))
end
function Base.union(G₁::Group, G₂::Group)
    G₁ == G₂ && return G₁
    return Group(elements(G₁)..., elements(G₂)...)
end

Base.hash(g::Group, h::UInt) = hash(g.hash, h)

_orbit(sym::Group{1}, k::T) where {T<:Integer} = Set{T}(g.lattice_aut(k) for g ∈ elements(sym))
_orbit(sym::Group{N}, k::NTuple{N,T}) where {N,T<:Integer} = Set{NTuple{N,T}}(g.lattice_aut(k) for g ∈ elements(sym))

function _orbit_representatives(sym::Group, inds) # slow
    sym_elements = elements(sym)
    T_k = eltype(inds)
    k_reps = Vector{T_k}(undef, length(inds))
    for (i, k) ∈ enumerate(inds)
        k_rep = k
        for g ∈ sym_elements
            k_g = g.lattice_aut(k)
            if k_g > k_rep
                k_rep = k_g
            end
        end
        @inbounds k_reps[i] = k_rep
    end
    return k_reps
end

function _filter_valid_representatives(sym::Group, k_reps)
    sym_elements = elements(sym)
    T_k = eltype(k_reps)
    reps = T_k[]
    seen_reps = Set{T_k}()
    for k_rep ∈ k_reps
        k_rep in seen_reps && continue
        push!(seen_reps, k_rep)

        is_valid_orbit = true # if `k` maps to itself and has a conflicting phase, then it is not a valid orbit
        for g ∈ sym_elements
            if g.lattice_aut(k_rep) == k_rep && g.cocycle(k_rep) != 1
                is_valid_orbit = false
                break
            end
        end
        if is_valid_orbit
            push!(reps, k_rep)
        end
    end
    return _sort_representatives!(reps)
end

_sort_representatives!(reps::Vector{<:Integer}) = sort!(reps)
_sort_representatives!(reps::Vector{<:NTuple{N,Integer}}) where {N} = sort!(reps; by = reverse)

function _compute_action_map(sym::Group, inds, k_reps)
    sym_elements = elements(sym)
    return map(enumerate(inds)) do (i, k)
        # invariance under `g` reads a_k = α_g(k) a_{β_g(k)}, so the element to look for is the
        # one carrying `k` onto its representative, and the factor is its cocycle *at k*
        k_rep = k_reps[i]
        for g ∈ sym_elements
            if g.lattice_aut(k) == k_rep
                return (k_rep, g.cocycle(k))
            end
        end
        return throw(ArgumentError("Symmetry group consistency error"))
    end
end



#

const NoSymSpace = Union{BaseSpace,TensorSpace}

const _orbit_cache = Dict{Tuple{Any,Group},Tuple{Any,Vector}}()
const _orbit_cache_lock = ReentrantLock()

# helper functions for type inference
_indices_type(::Type{<:BaseSpace}) = StepRange{Int,Int}
_indices_type(::Type{<:TensorSpace{<:NTuple{N,BaseSpace}}}) where {N} = Vector{NTuple{N,Int}}
_rep_idx_action_type(::Type{S}, ::Type{Group{N,T}}) where {S<:NoSymSpace,N,T} =
    Tuple{eltype(_indices_type(S)),Base.promote_op((v, k) -> v(k), Cocycle{N,T}, eltype(_indices_type(S)))}

"""
    SymmetricSpace(space::SequenceSpace, sym::Group)
    SymmetricSpace(space::SequenceSpace)

Restriction of `space` to the subspace invariant under `sym`, storing one
coefficient per orbit. With no group given, the trivial one is used.

`indices` returns the orbit representatives, so `dimension` shrinks accordingly,
and norms account for the multiplicity of each orbit. Some symmetries are
available through [`evensym`](@ref), [`oddsym`](@ref) and [`d4sym`](@ref); build
a [`Group`](@ref) directly for anything else.

Fields:
- `space :: S`
- `symmetry :: G`

See also: [`desymmetrize`](@ref), [`symmetry`](@ref) and [`Group`](@ref).
"""
struct SymmetricSpace{S<:NoSymSpace,G<:Group,I,R} <: SequenceSpace
    space    :: S
    symmetry :: G
    indices  :: I
    rep_idx_action :: Vector{R}
    function SymmetricSpace(space::S, sym::G) where {S<:NoSymSpace,G<:Group}
        inds = indices(space)
        inds2, rep_idx_action = lock(_orbit_cache_lock) do
            get!(_orbit_cache, (inds, sym)) do
                k_reps = _orbit_representatives(sym, inds)
                reps = _filter_valid_representatives(sym, k_reps)
                (_reps_indices(reps), _compute_action_map(sym, inds, k_reps))
            end
        end
        TI = _indices_type(S)
        TR = _rep_idx_action_type(S, G)
        isconcretetype(TR) && return new{S,G,TI,TR}(space, sym, inds2::TI, rep_idx_action::Vector{TR})
        return new{S,G,TI,eltype(rep_idx_action)}(space, sym, inds2::TI, rep_idx_action)
    end
end

_reps_indices(v::Vector) = v # tensor case: tuple representatives stay as a plain vector
function _reps_indices(v::Vector{Int})
    n = length(v)
    n == 0 && return 1:1:0
    n == 1 && return @inbounds v[1]:1:v[1]
    @inbounds d = v[2] - v[1]
    @inbounds for i ∈ 3:n
        v[i] - v[i-1] == d || return throw(ArgumentError("the representatives do not form an arithmetic progression: the symmetry group is inconsistent"))
    end
    return @inbounds v[1]:d:v[n]
end

SymmetricSpace(space::NoSymSpace) = SymmetricSpace(space, symmetry(space))

SymmetricSpace(space::SymmetricSpace) = space

SymmetricSpace(space::SymmetricSpace, sym::Group) = SymmetricSpace(desymmetrize(space), symmetry(space) ∪ sym)

"""
    desymmetrize(s::VectorSpace)

Return the underlying space of `s` without its symmetry. Acts as the identity on
a space that carries no symmetry.

# Examples

```jldoctest
julia> desymmetrize(evensym(Fourier(3, 1.0)))
Fourier(3, 1.0)

julia> desymmetrize(Taylor(2))
Taylor(2)
```

See also: [`SymmetricSpace`](@ref) and [`symmetry`](@ref).
"""
desymmetrize(s::SymmetricSpace) = s.space
desymmetrize(s::NoSymSpace) = s
desymmetrize(s::ScalarSpace) = s
desymmetrize(s::CartesianPower) = CartesianPower(desymmetrize(space(s)), nspaces(s))
desymmetrize(s::CartesianProduct) = CartesianProduct(map(desymmetrize, spaces(s)))

"""
    symmetry(s::VectorSpace)

Return the [`Group`](@ref) that `s` is invariant under. A space carrying no
symmetry returns the trivial group.

See also: [`SymmetricSpace`](@ref), [`desymmetrize`](@ref) and
[`elements`](@ref).
"""
symmetry(s::SymmetricSpace) = s.symmetry
symmetry(::BaseSpace) = # identity
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(1)),
                       Cocycle(exact(1//1), StaticArrays.SVector{1,Rational{Int}}(0//1))))
symmetry(::TensorSpace{<:NTuple{N,BaseSpace}}) where {N} = # identity
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{N,N,Int}(I)),
                       Cocycle(exact(1//1), StaticArrays.SVector{N,Rational{Int}}(ntuple(_ -> 0//1, Val(N))))))

indices(s::SymmetricSpace) = s.indices

order(s::SymmetricSpace) = order(desymmetrize(s))
frequency(s::SymmetricSpace) = frequency(desymmetrize(s))

Base.:(==)(s₁::SymmetricSpace, s₂::SymmetricSpace) = (desymmetrize(s₁) == desymmetrize(s₂)) & (symmetry(s₁) == symmetry(s₂))
Base.issubset(s₁::SymmetricSpace, s₂::SymmetricSpace) = issubset(desymmetrize(s₁), desymmetrize(s₂)) & issubset(symmetry(s₂), symmetry(s₁))
Base.intersect(s₁::SymmetricSpace, s₂::SymmetricSpace) = SymmetricSpace(intersect(desymmetrize(s₁), desymmetrize(s₂)), union(symmetry(s₁), symmetry(s₂)))
Base.union(s₁::SymmetricSpace, s₂::SymmetricSpace) = SymmetricSpace(union(desymmetrize(s₁), desymmetrize(s₂)), intersect(symmetry(s₁), symmetry(s₂)))

Base.hash(s::SymmetricSpace, h::UInt) = hash(s.space, hash(s.symmetry, h))

function _findindex_constant(s::SymmetricSpace)
    k0 = _findindex_constant(desymmetrize(s))
    k0 ∈ indices(s) && return k0
    return nothing
end

function _findposition(k::Integer, s::SymmetricSpace{<:BaseSpace})
    # representative located by by arithmetic on the `StepRange`
    r = indices(s)
    i, rem = divrem(k - first(r), step(r))
    return iszero(rem) & (0 ≤ i < length(r)) ? i+1 : nothing
end
function _findposition(k::NTuple{N,Integer}, s::SymmetricSpace{<:TensorSpace{<:NTuple{N,BaseSpace}}}) where {N}
    # representative located by bisection on the vector of a `TensorSpace`
    inds = indices(s)
    i = searchsortedfirst(inds, k; by = reverse)
    return (i ≤ length(inds)) && (@inbounds inds[i] == k) ? i : nothing
end
_findposition(u::AbstractRange, s::SymmetricSpace) = map(i -> _findposition(i, s), u)
_findposition(u::AbstractVector, s::SymmetricSpace) = map(i -> _findposition(i, s), u)
_findposition(c::Colon, ::SymmetricSpace) = c

_iscompatible(s₁::SymmetricSpace, s₂::SymmetricSpace) = _iscompatible(desymmetrize(s₁), desymmetrize(s₂)) # & (symmetry(s₁) == symmetry(s₂))
_iscompatible(s₁::SymmetricSpace, s₂::NoSymSpace) = _iscompatible(desymmetrize(s₁), s₂)
_iscompatible(s₁::NoSymSpace, s₂::SymmetricSpace) = _iscompatible(s₁, desymmetrize(s₂))

IntervalArithmetic.interval(::Type{T}, s::SymmetricSpace) where {T<:IntervalArithmetic.NumTypes} = SymmetricSpace(interval(T, desymmetrize(s)), interval(symmetry(s)))
IntervalArithmetic.interval(s::SymmetricSpace) = SymmetricSpace(interval(desymmetrize(s)), interval(symmetry(s)))
# IntervalArithmetic._infer_numtype(s::SymmetricSpace) = IntervalArithmetic._infer_numtype(desymmetrize(s))
# IntervalArithmetic._interval_infsup(::Type{T}, s₁::SymmetricSpace, s₂::SymmetricSpace, d::IntervalArithmetic.Decoration) where {T<:IntervalArithmetic.NumTypes} =
#     SymmetricSpace(IntervalArithmetic._interval_infsup(T, desymmetrize(s₁), desymmetrize(s₂), d), intersect(interval(symmetry(s₁)), interval(symmetry(s₂))))

IntervalArithmetic.interval(g::Group) = unsafe_group!(Set(interval(h) for h in elements(g)))
IntervalArithmetic.interval(g::GroupElement) = GroupElement(g.lattice_aut, interval(g.cocycle))
IntervalArithmetic.interval(g::Cocycle) = Cocycle(interval(g.amplitude), g.phase)

# tensor product

⊗(g₁::GroupElement{N₁}, g₂::GroupElement{N₂}) where {N₁,N₂} = GroupElement(
    LatticeAut(hcat(vcat(g₁.lattice_aut.matrix, zero(StaticArrays.SMatrix{N₂,N₁,Int})),
                     vcat(zero(StaticArrays.SMatrix{N₁,N₂,Int}), g₂.lattice_aut.matrix))),
    Cocycle(g₁.cocycle.amplitude * g₂.cocycle.amplitude,
               vcat(g₁.cocycle.phase, g₂.cocycle.phase)))

⊗(G₁::Group, G₂::Group) = unsafe_group!(Set(g₁ ⊗ g₂ for g₁ ∈ elements(G₁), g₂ ∈ elements(G₂)))

⊗(s₁::SymmetricSpace, s₂::SymmetricSpace) =
    SymmetricSpace(desymmetrize(s₁) ⊗ desymmetrize(s₂), symmetry(s₁) ⊗ symmetry(s₂))
⊗(s₁::SymmetricSpace, s₂::NoSymSpace) = s₁ ⊗ SymmetricSpace(s₂)
⊗(s₁::NoSymSpace, s₂::SymmetricSpace) = SymmetricSpace(s₁) ⊗ s₂

#

_prettystring(s::SymmetricSpace{<:TensorSpace}, iscompact::Bool) = string("(", _prettystring(desymmetrize(s), iscompact), ")_sym")
_prettystring(s::SymmetricSpace, iscompact::Bool) = string(_prettystring(desymmetrize(s), iscompact), "_sym")



#

"""
    evensym(s::BaseSpace)

Restrict `s` to the subspace of sequences invariant under the natural involution
of its basis:
- `Fourier`: identifies the modes `k` and `-k`, keeping `k ≥ 0` (cosine series).
- `Taylor` and `Chebyshev`: keeps the even orders only.

# Examples

```jldoctest
julia> collect(indices(evensym(Fourier(3, 1.0))))
4-element Vector{Int64}:
 0
 1
 2
 3

julia> collect(indices(evensym(Taylor(4))))
3-element Vector{Int64}:
 0
 2
 4
```

See also: [`oddsym`](@ref), [`d4sym`](@ref) and [`SymmetricSpace`](@ref).
"""
evensym(s::Taylor) = SymmetricSpace(s,
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(1)),
                       Cocycle(exact(1//1), StaticArrays.SVector{1,Rational{Int}}(1//1)))))
evensym(s::Fourier) = SymmetricSpace(s,
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(-1)),
                       Cocycle(exact(1//1), StaticArrays.SVector{1,Rational{Int}}(0//1)))))
evensym(s::Chebyshev) = SymmetricSpace(s,
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(1)),
                       Cocycle(exact(1//1), StaticArrays.SVector{1,Rational{Int}}(1//1)))))

"""
    oddsym(s::BaseSpace)

Restrict `s` to the subspace of sequences anti-invariant under the natural
involution of its basis:
- `Fourier`: identifies the modes `k` and `-k` together with a sign flip, keeping `k > 0` (since series).
- `Taylor` and `Chebyshev`: keeps the odd orders only.

# Examples

```jldoctest
julia> collect(indices(oddsym(Fourier(3, 1.0))))
3-element Vector{Int64}:
 1
 2
 3

julia> collect(indices(oddsym(Taylor(4))))
2-element Vector{Int64}:
 1
 3
```

See also: [`evensym`](@ref), [`d4sym`](@ref) and [`SymmetricSpace`](@ref).
"""
oddsym(s::Taylor)  = SymmetricSpace(s,
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(1)),
                       Cocycle(exact(-1//1), StaticArrays.SVector{1,Rational{Int}}(1//1)))))
oddsym(s::Fourier)  = SymmetricSpace(s,
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(-1)),
                       Cocycle(exact(-1//1), StaticArrays.SVector{1,Rational{Int}}(0//1)))))
oddsym(s::Chebyshev)  = SymmetricSpace(s,
    Group(GroupElement(LatticeAut(StaticArrays.SMatrix{1,1,Int}(1)),
                       Cocycle(exact(-1//1), StaticArrays.SVector{1,Rational{Int}}(1//1)))))

#

"""
    d4sym(s::TensorSpace{<:Tuple{<:Fourier,<:Fourier}})

Restrict a two-dimensional Fourier space to the subspace invariant under the
dihedral group ``D_4``, i.e., the symmetries of the square, generated by a
quarter turn and a diagonal reflection.

# Examples

```jldoctest
julia> s = Fourier(2, 1.0) ⊗ Fourier(2, 1.0)
Fourier(2, 1.0) ⊗ Fourier(2, 1.0)

julia> indices(d4sym(s))
6-element Vector{Tuple{Int64, Int64}}:
 (0, 0)
 (1, 0)
 (2, 0)
 (1, 1)
 (2, 1)
 (2, 2)
```

See also: [`evensym`](@ref), [`oddsym`](@ref) and [`SymmetricSpace`](@ref).
"""
d4sym(s::TensorSpace{T}) where {T<:Tuple{<:Fourier,<:Fourier}} = SymmetricSpace(s,
    Group(
        GroupElement(LatticeAut(StaticArrays.SMatrix{2,2,Int}([0 -1 ; 1 0])),
                       Cocycle(exact(1//1), StaticArrays.SVector{2,Rational{Int}}(0//1, 0//1))),
        GroupElement(LatticeAut(StaticArrays.SMatrix{2,2,Int}([0  1 ; 1 0])),
                       Cocycle(exact(1//1), StaticArrays.SVector{2,Rational{Int}}(0//1, 0//1)))))
